name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Adding README - Chinese Traditional
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
